analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    avoid_print: ignore
    avoid_redundant_argument_values: ignore
    document_ignores: ignore
    flutter_style_todos: ignore
    lines_longer_than_80_chars: ignore
    use_if_null_to_convert_nulls_to_bools: ignore
include: package:very_good_analysis/analysis_options.7.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
