analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    lines_longer_than_80_chars: ignore
include: package:very_good_analysis/analysis_options.7.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
